[debug]
debug_n_rows = 0

[directories]
# Absolute path to root directory for UMLS source files
umls_dir=/Users/jas971/documents/2026AA/2026AA

output_dir=/Users/jas971/documents/UBKG_JKG

[json_out]
# name of output file
output_filename=jkg.json

# pretty print
pretty=false
# indentation for pretty printing
indent=4

[cui_nans]
# CUIs for which related terms contain the string "NaN" string
# as a legitimate term that is not to be confused with Python NaN.
# C1419854="SCN11A/NaN", C5958837="SCN11A wt allele"
cui_nans=C1419854,C5958837

[columns]
# Column headers for UMLS files, in the order in which they appear in the file
MRREL=CUI1,AUI1,STYPE1,REL,CUI2,AUI2,STYPE2,RELA,RUI,SRUI,SAB,SL,RG,DIR,SUPPRESS,CVF
MRDOC=DOCKEY,VALUE,TYPE,EXPL
MRSAB=VCUI,RCUI,VSAB,RSAB,SON,SF,SVER,VSTART,VEND,IMETA,RMETA,SLC,SCC,SRL,TFR,CFR,CXTY,TTYL,ATNL,LAT,CENC,CURVER,SABIN,SSN,SCIT
MRCONSO=CUI,LAT,TS,LUI,STT,SUI,ISPREF,AUI,SAUI,SCUI,SDUI,SAB,TTY,CODE,STR,SRL,SUPPRESS,CVF
MRDEF=CUI,AUI,ATUI,SATUI,SAB,DEF,SUPPRESS,CVF
SRDEF=RT,UI,STY_RL,STN_RTN,DEF,EX,UN,NH,ABR,RIN
MRSTY=CUI,TUI,STN,STY,ATUI,CVF
SRSTRE1=UI1,UI2,UI3
MRSAT=CUI,LUI,SUI,METAUI,STYPE,CODE,ATUI,SATUI,ATN,SAB,ATV,SUPPRESS,CVF

[rowsizes]
# Size of a sample row in each file, for estimating number of rows in files
MRREL=92
MRDOC=126
MRSAB=546
MRCONSO=118
MRDEF=264
SRDEF=293
MRSTY=71
SRSTRE1=15
MRSAT=84

[scanestimates]
# Estimates for scanning times of files, in seconds.
# (tqdm does not work with polar's scan_csv function).
os=MacOs
memory=32GB
MRREL=50
MRCONSO=10
MRSAB=1
MRDEF=1
SRDEF=1
MRSAT=80

[progress_labels]
# Strings used in progress indicators for both reading and writing
node_source=Source
node_semantic_rel=Semantic Network Rel_Label
node_rel=concept-to-concept Rel_Label
node_concept=Concept
node_term=Term
rel_semantic=Semantic Network
rel_concept_concept=concept-to-concept
rel_concept_code=concept-to-code
rel_ndc=NDC code

[refseq]
refseq_url=https://ftp.ncbi.nlm.nih.gov/gene/DATA/gene_info.gz





